jenkins_prefer_lts: false
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

# Plugin list can use the plugin name, or a name/version dict.
jenkins_plugins:
    - javax-activation-api
    - javax-mail-api
    - sshd
    - cloudbees-folder
    - antisamy-markup-formatter
    - structs
    - token-macro
    - build-timeout
    - credentials
    - trilead-api
    - ssh-credentials
    - workflow-step-api
    - plain-credentials
    - credentials-binding
    - scm-api
    - workflow-api
    - timestamper
    - caffeine-api
    - script-security
    - snakeyaml-api
    - jackson2-api
    - plugin-util-api
    - font-awesome-api
    - popper2-api
    - bootstrap5-api
    - jquery3-api
    - echarts-api
    - display-url-api
    - workflow-support
    - checks-api
    - junit
    - matrix-project
    - resource-disposer
    - ws-cleanup
    - ant
    - jaxb
    - durable-task
    - workflow-durable-task-step
    - jdk-tool
    - command-launcher
    - bouncycastle-api
    - ace-editor
    - workflow-scm-step
    - workflow-cps
    - workflow-job
    - apache-httpcomponents-client-4-api
    - mailer
    - workflow-basic-steps
    - gradle
    - pipeline-milestone-step
    - pipeline-build-step
    - pipeline-stage-step
    - pipeline-model-api
    - pipeline-model-extensions
    - variant
    - jsch
    - git-client
    - git-server
    - workflow-cps-global-lib
    - branch-api
    - workflow-multibranch
    - pipeline-stage-tags-metadata
    - pipeline-input-step
    - pipeline-model-definition
    - lockable-resources
    - workflow-aggregator
    - jjwt-api
    - okhttp-api
    - github-api
    - git
    - github
    - github-branch-source
    - pipeline-github-lib
    - pipeline-graph-analysis
    - pipeline-rest-api
    - handlebars
    - momentjs
    - pipeline-stage-view
    - ssh-slaves
    - matrix-auth
    - pam-auth
    - ldap
    - email-ext


jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: "/var/lib/jenkins/secrets/initialAdminPassword"

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }} --httpListenAddress=127.0.0.1"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

# If Jenkins is behind a proxy, configure this.
jenkins_proxy_host: "http://localhost/jenkins"
jenkins_proxy_port: "80"
jenkins_proxy_noproxy:
  - "127.0.0.1"
  - "localhost"