- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Ensure nginx is running
  service:
    name: nginx
    enabled: yes
    state: started
- name: Create config file
  template:
    src: jenkins.conf
    dest: /etc/nginx/sites-available/jenkins.conf
- name: Create logs repertory
  file:
    path: "/var/log/nginx/jenkins"
    state: directory
    mode: '0755'
- name: Activate config
  file:
    src: /etc/nginx/sites-available/jenkins.conf
    dest: /etc/nginx/sites-enabled/jenkins.conf
    state: link
- name: Restart nginx
  service:
    name: nginx
    state: restarted