- name: Disable CrumbIssuer - define script
  set_fact:
    disableCsrfProtection: |
        import hudson.security.csrf.DefaultCrumbIssuer
        import jenkins.model.Jenkins
        if (!Jenkins.instance.isQuietingDown()) {
            def j = Jenkins.instance
            if (j.getCrumbIssuer() != null) {
                j.setCrumbIssuer(null)
                j.save()
            }
        }
- name: Disable CrumbIssuer - execute script
  jenkins_script:
    script: "{{ disableCsrfProtection }}"
    url: http://localhost:8080/
    user: admin
    password: admin
- name: Create jenkins job for BACK
  jenkins_job:
    config: "{{ lookup('file', 'templates/backend-job.xml') }}"
    name: Backend Job
    password: admin
    url: http://localhost:8080/
    user: admin
- name: Create jenkins jor for FRONT
  jenkins_job:
    config: "{{ lookup('file', 'templates/frontend-job.xml') }}"
    name: Frontend Job
    password: admin
    url: http://localhost:8080/
    user: admin
    