- name: apt-get update
  apt:
    upgrade: yes
    update_cache: yes
- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
      - openjdk-11-jre-headless
    state: present